# Generated by Django 5.2.11 on 2026-04-10 12:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации')),
                ('starting_at', models.DateTimeField(verbose_name='Дата и время начала')),
                ('finishing_at', models.DateTimeField(verbose_name='Дата и время завершения')),
                ('creator', models.CharField(blank=True, null=True, verbose_name='Автор')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='Рейтинг')),
                ('status', models.CharField(choices=[('pending', 'Ещё не началось'), ('going', 'Идёт сейчас'), ('ended', 'Закончилось')], default='pending', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('coordinates', models.TextField(verbose_name='Координаты')),
            ],
            options={
                'verbose_name': 'Место проведения мероприятия',
                'verbose_name_plural': 'Места проведения мероприятий',
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='event_images', verbose_name='Изображение')),
                ('image_preview', models.FileField(upload_to='event_images', verbose_name='Превью изображение')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='event_app.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Изображение мероприятия',
                'verbose_name_plural': 'Изображения мероприятий',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event_app.eventlocation', verbose_name='Место проведения'),
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(60)], verbose_name='Температура, в градусах Цельсия')),
                ('humidity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Влажность воздуха, в процентах')),
                ('atmospheric_pressure', models.IntegerField(validators=[django.core.validators.MinValueValidator(650), django.core.validators.MaxValueValidator(820)], verbose_name='Атмосферное давление, в мм ртутного столба')),
                ('wind_direction', models.CharField(choices=[('north', 'Северный'), ('north-east', 'Северо-восточный'), ('east', 'Восточный'), ('south-east', 'Юго-восточный'), ('south', 'Южный'), ('south-west', 'Юго-западный'), ('west', 'Западный'), ('north-west', 'Северо-западный')], default='north', verbose_name='Направление ветра')),
                ('wind_speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скорость ветра, в м/с')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='event_app.eventlocation')),
            ],
            options={
                'verbose_name': 'Погода в месте проведения мероприятия',
                'verbose_name_plural': 'Погода в местах проведения мероприятий',
            },
        ),
    ]
