# Generated by Django 5.2.11 on 2026-04-10 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('name', 'starting_at', 'finishing_at'), 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterField(
            model_name='event',
            name='published_at',
            field=models.DateTimeField(verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='event_app.eventlocation', verbose_name='Место проведения мероприятия'),
        ),
    ]
