# Generated by Django 5.2.11 on 2026-04-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_alter_event_options_alter_event_published_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimage',
            name='image_preview',
        ),
    ]
