# Generated by Django 5.2.11 on 2026-04-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_remove_eventimage_image_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='finishing_at',
            field=models.DateTimeField(verbose_name='Дата и время завершения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='published_at',
            field=models.DateTimeField(verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starting_at',
            field=models.DateTimeField(verbose_name='Дата и время начала'),
        ),
    ]
