# Generated by Django 5.2.11 on 2026-04-14 08:33

import common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_alter_event_finishing_at_alter_event_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='event',
            name='finishing_at',
            field=models.DateTimeField(validators=[common.validators.NotPastDateTimeValidator()], verbose_name='Дата и время завершения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='published_at',
            field=models.DateTimeField(validators=[common.validators.NotPastDateTimeValidator()], verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starting_at',
            field=models.DateTimeField(validators=[common.validators.NotPastDateTimeValidator()], verbose_name='Дата и время начала'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='event_app.eventlocation', verbose_name='Место проведения мероприятия'),
        ),
    ]
