# Generated by Django 5.2.11 on 2026-04-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_alter_event_creator_alter_event_finishing_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlocation',
            name='coordinates',
            field=models.CharField(max_length=255, verbose_name='Координаты'),
        ),
    ]
